### ISSUE TITLE
Boosterpack using two items at once

### ISSUE THREAD

**Issue by EmperorSaltYT** [KamuiKody/k-pokemontcg#13]
When you have multiple packs in your inventory, using one will consume two and give twice the amount of pulled cards

**Comment by Botman64** [comment]
Most likely self inflicted join the discord for more support

**Comment by EmperorSaltYT** [comment]
This issue fixed itself with some slight tinkering.

**Comment by bonecollecter305** [comment]
can anyone tell me the steps to install this on my fivem server?
