### ISSUE TITLE
cards wont go off screen HELP please

### ISSUE THREAD

**Issue by lifewithchris** [KamuiKody/k-pokemontcg#16]
once we open the booster pack it gives the same card and one you press backspace or esc it keep mouse on screen and you have to fly out to fix, could you help please

**Comment by lifewithchris** [comment]
is the away to have it so it doesnt show cards on screen and just puts them into inv that would stop the freezing

**Comment by NEMASIS50** [comment]
ok so i found the problem for some reason renaming the folder screws up the file so just keep it like this 
ensure k-pokemontcg and it should work fine it also fixes the same card in one pack issues as well
