### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by FBFezz** [KamuiKody/k-pokemontcg#5]
Add a Folder / Binder item you can put the cards into and flick through

Add an option for Shiny Cards

**Comment by Botman64** [comment]
get the tebex version i sell
it has a binder and is the only place im doing future updates thank you!

**Comment by FBFezz** [comment]
Is there an esx version? And how much is it on tebex?

**Comment by Botman64** [comment]
unfortunately  i only work with qb-core for now its 0.01 dollars lol i think tebex makes u spend like 75 cents tho
it does not work with esx though

**Comment by FBFezz** [comment]
Any chance i could try convert it if i pay for it? can send you the file after if i get it working

**Comment by Botman64** [comment]
if you convert the github version and send it to me ill look into converting the part of the tebex version that is escrowed since its only four events

**Comment by FBFezz** [comment]
Alright will do, thanks

**Comment by FBFezz** [comment]
Made a PR but still wip, nearly done tho But with esx version can you give support for ox_inventory, it has a docs and is the inventory that is free that esx people use that has metadata built in
