### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by w4fflz** [KamuiKody/k-pokemontcg#7]
![image](https://user-images.githubusercontent.com/96218191/180103355-78e93a03-78ea-4f06-b9ee-9994a075ceae.png)

Getting this error on drag and drop

**Comment by Botman64** [comment]
need to update the file

**Comment by w4fflz** [comment]
How?

**Comment by SoulReaper4720** [comment]
> How?

Add the qbcore export in the file for the GetCoreObject.
